---
title: "Dynamic Tabs"
author: "Mark Gingrass"
date: "`r Sys.Date()`"
output:
 html_document:
   df_print: paged
   toc: yes
   toc_depth: '3'
 html_notebook:
   code_folding: hide
   theme: united
   toc: yes
   toc_depth: 3
   toc_float: yes
keep_md: TRUE
---

<iframe width="560" height="315" src="https://youtube.com/embed/KMTWjPLEolc" frameborder="0" allowfullscreen></iframe>

### Header 

Talk about this data here. 

```{r}
library(ggplot2)
my_data <- mtcars

p_list <- list()

p1 <- qplot(mpg, disp, data = my_data[1:10,])
p2 <- qplot(disp, mpg, data = my_data[10:20,])

p1 <- ggplot(my_data[1:10,], aes(x = disp, y = mpg))+
  geom_point()

p_list[[1]] <- list(p1, "First Plot")
p_list[[2]] <- list(p2, "Second Plot")
```

```{r, echo = FALSE}
p_list <- list()
 ged.min <- read.csv("C:/GIT/ged-project/data/ged_min_dat.csv")
 levels(ged.min$site)
for (i in 1:length(levels(ged.min$site))){
  ppt <- ggplot(ged.min[ged.min$site == levels(ged.min$site)[i] ,], 
                    aes(y = n, x = year)) +
        geom_point() +
        geom_line() +
        facet_grid(site ~ grid.id) +
        theme_bw()
 
    p_list[[i]] <- list(ppt, levels(ged.min$site)[i])
    } #i




```


### MY plots :)  {.tabset}

```{r echo=FALSE, results='asis'}
for (i in seq_along(p_list)){
 tmp <- p_list[[i]]
 cat("####", tmp[[2]], "\n")
 print(tmp[1])
 cat('\n\n')
}
```
